project_id = "pnryoptppeptcgsfgjyr"

[functions.submit-contact]
verify_jwt = false

[functions.ai-video-ideas]
verify_jwt = false

[functions.ai-script-analyzer]
verify_jwt = false

[functions.ai-thumbnail-generator]
verify_jwt = false
